#!/usr/bin/env bash

set -e

# Create out vpc

VPC_ID=$(aws ec2 create-vpc --cidr-block 172.31.0.0/16 \
--tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-3}]" \
--region eu-west-2 \
--query Vpc.VpcId \
--output text)

# Turn on DNS Hostnames
aws ec2 modify-vpc-attribute --vpc-id $VPC_ID \
--enable-dns-hostnames "{\"Value\":true}"

# Create an IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text
)

# Attach an IGW
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Create an new subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block 172.31.0.0/20 \
--query Subnet.SubnetId \
--output text)

# Auto assign IPv4 addresses
aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch


# Explicitly associate subnet
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query "RouteTables[].RouteTableId[]" \
--output text)

ASSOC_ID=$(aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID \
--query AssociationId \
--output text)

# Add a route for our RT to our IGW
aws ec2 create-route --route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 --gateway-id $IGW_ID

echo ./delete_vpc $VPC_ID $ASSOC_ID $IGW_ID $SUBNET_ID $RT_ID 