#!/usr/bin/env bash
echo "== delete object"

# Exit when error raised
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# # Approach 1: simple approach that uses cli
# aws s3 rm s3://$BUCKET_NAME --recursive


# Approach 2: you can use s3api delete-object, but it is more complicated
aws s3api list-objects \
--bucket $BUCKET_NAME \
--query "Contents[].Key" \
| jq -n '{Objects: [ inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json