#! /usr/bin/env bash
echo "== list newest bucket"

# List top 5 bucket names, sort by CreationDate in descending order, get names only
 aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | .Name'