#!/usr/bin/env bash
echo "== sync"

# Exit when error raised
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove the folder if it already exists
rm -r $OUTPUT_DIR

# Ensure the output directory exisits
# The -p flag creates the /home, /home/demo, and /home/demo/sub2 directories if they do not already exist.
mkdir -p $OUTPUT_DIR

# Create random number between 1 and 10
NUM_FILES=$((RANDOM % 6 + 5))

echo "Creating $NUM_FILES random files..."

for ((i=1; i<=$NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="${OUTPUT_DIR}/${FILENAME_PREFIX}_${i}.txt"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1 )) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files